[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.4.0"

[[constraint]]
  name = "pack.ag/amqp"
  version = "0.12.0"

[prune]
  go-tests = true
  unused-packages = true
