[[constraint]]
  name = "github.com/incpac/quiet"
  version = "0.2.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[constraint]]
  name = "pack.ag/amqp"
  version = "0.12.0"

[prune]
  go-tests = true
  unused-packages = true
